name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "fifa 26"
  comment: "fifa 26"
  url: "https://trashbytes.net/dl/QLgxXR4_GHBbwixRY4f_JaA7Yvz92BdJdNgq2IGMKLWC1t75csx81urT7xRYMCuxi7OM_nXHABMU47Xy8UEgEZGGGGNXSvsx-XIJ40HT1crpJjC3EzUDI0FP?v=1761601213-qCZ7DuWwXkWHohX9QSQrUCQKUPrBtxpoGGGLPvDlnnY%3D"
  file_name: "EA SPORTS FC 26.7z.001"
  piece_size: 24 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
